### PR TITLE
added utility function to WebDAVFileProvider to get the etag from xml data

### PR DESCRIPTION
**Pull request by skela**

### CODE REVIEW

**Comment by amosavian** [comment]
I don't know how you use this function but I recommend to downcast result of `contentsOfDirectory` or `attributesOfItem` to `WebDAVFileObject` and use `.entryTag` property.

**Comment by skela** [comment]
No @amosavian I can't, the observer logic isn't inside the provider class, so I need this to be in a static function somewhere. If you don't like it to be in WebDAVFileProvider, then let me know a place I can stick it. I don't mind, if no place fits, I can stick it in a utility class instead, but I do need this to be in the library since you don't like to make the xml classes public.

**Comment by amosavian** [comment]
This code is dirty as is reinventing algorithm I implemented in `DavResponse.parse(xmlResponse:, baseURL: )` and `WebDavFileObject`. Also I can't get how user can use this function as FileProvider doesn't return any xml to user. If you describe more I can find a way to integrate.

**Comment by skela** [comment]
It invents because I only need the etag, and later on, when I have time, I will make it so the app only downloads etag info when checking for changes to keep the observation calls very very light (which they need to be).

DavResponse is an internal class, like you tend to do with most of your classes, which is actually frustratingly annoying, because it prevents people from pitching in without working directly in the library code. Something we can't do easily if we want to keep things up to date as you change stuff.

If you have an alternate place to put it let me know, all I need is the ETag from supplied XML Data. Something I cannot do atm with your current private / internal restrictions.

**Comment by amosavian** [comment]
I think this PR has internal access. 🤔 Doesn't?

I think you need an alternative implementation of `attributesOfItem(path:, completionHandler:)` which returns etag only.  Correct me if I'm wrong.

**Comment by skela** [comment]
No, this PR does not have internal access.

No, I need much more fine-grained control over the call than just an alternative implementation of attributesOfItem, it needs to be easy to start and stop, and it needs to be separate from the normal code.

Perhaps one day when I can manage to insert the observation stuff (which I've written for both the Dropbox provider and the WebDav providers), this can be removed. But until then, I need some way to get the etag from the xml data from outside your library module. Because at present, this is impossible (and I don't understand why it needs to be).

**Comment by skela** [comment]
No worries, I can stick this in a branch instead

**Comment by amosavian** [comment]
This PR you have made is modifying `WebDAVFileProvider` directly and has both internal and fileprivate access.

There is an explanation to keep things internal. I refactor these APIs frequently and they are not stable. I have to guarantee that developers code won't break and thats why I add deprecated and obsoleted availability attribute to methods that are intended to be removed. Making these internal stuff public means I can't refactor and change them anymore.

**Comment by skela** [comment]
Nah man, check it out, the stuff I added was specifically public because I had to work around your private/internal crap anyway. But yeah I get it, no worries, I've added it to a branch, on my fork, that way I can work on the observer stuff at my own pace without too much of an issue.

**Comment by amosavian** [comment]
@skela please find new argument for `attributesOfItem` method of WebDav provider which allows to get only entryTag property from server.

**Pull request closed without merging**
