### PR TITLE
OneDrive: Fixed file downloading progress, disabling gzip compression

### PR DESCRIPTION
**Pull request by evilutioner**

### CODE REVIEW

**Comment by amosavian** [comment]
`Sources/FileProviderExtensions.swift` is moved to `Extensions/FoundationExtensions.swift`. Please pull and update your fork.

**Comment by evilutioner** [comment]
Sorry, I don't have permissions to perform merge

**Comment by amosavian** [comment]
Indeed I mean there is conflict because I moved file. Please update your fork and update this PR.

**Comment by evilutioner** [comment]
It needs some time... I am not ready update to ver 0.20

**Comment by amosavian** [comment]
Ok. No problem.

**Comment by amosavian** [comment]
@evilutioner please check [These lines](https://github.com/amosavian/FileProvider/blob/master/Sources/Extensions/FoundationExtensions.swift#L219-L224). I've added some new methods suitable for your case, e.g:

```swift
request.set(httpAcceptEncoding: .gzip)
// OR
request.set(httpAcceptEncoding: Quality(.gzip, 0))
```

**Comment by amosavian** [comment]
Apple says in [Foundation iOS 11 release notes](https://developer.apple.com/library/content/releasenotes/Foundation/RN-Foundation/index.html):

> New in macOS, iOS, watchOS, and tvOS is URLSession support for HTTP brotli content encoding (). HTTP requests by default will contain a “br” value (in addition to gzip and deflate) for the “Accept-Encoding” HTTP header; this informs the web server that the user agent supports brotli encoding. The web server can send an HTTP body with “Content-Encoding: br” HTTP header to indicate that the content is brotli-encoded. URLSession will automatically decompress the HTTP body data — passing the decoded data back to the client in didReceiveData delegate callbacks or via a Data object for the convenience URLSession APIs — just like it does for “Content-Encoding: gzip” content.

It means NSURLSession already tries to download gzip version if available. I think this PR is redundant unless you know something that I don't.

**Comment by evilutioner** [comment]
@amosavian I checked on iOS 10 and NSURLSession really has default header "gzip, deflate". I retested Dropbox, OneDrive and Google Drive (I implemented just a few API requests) and just Google Drive REST API has this issue. Google drive returns NSURLSessionTransferSizeUnknown for "gzip, deflate" and correct size for "gzip;q=0" It means the key of this issue is "deflate" mode compression and it needs more investigations... May be I mistaken about OneDrive issue

**Comment by amosavian** [comment]
Google Drive supports brotli compression method which is supported by iOS 11 / macOS 10.13.

PS: brotli developed by Google.
PS2: I didn’t implemented GDrive yet!

**Comment by evilutioner** [comment]
I reproduced today this issue with OneDrive. The config "gzip;q=0" prohibit gzip compression. More about this: https://github.com/expressjs/compression/issues/52

**Comment by amosavian** [comment]
Please check these scenarios on OneDrive:
`deflate;q=1.0, gzip;q=0.5`
`gzip;q=1.0, deflate;q=0.5`
`deflate;q=1.0, identity;q=0.5`
`gzip;q=1.0, identitiy;q=0.5`

**Comment by evilutioner** [comment]
@amosavian I can check it after 2 weeks

**Comment by amosavian** [comment]
I'll keep it open then.

**Comment by evilutioner** [comment]
@amosavian About progress in OneDrive:
deflate;q=1.0, gzip;q=0.5 - yes
gzip;q=1.0, deflate;q=0.5 - no
deflate;q=1.0, identity;q=0.5 - yes
gzip;q=1.0, identitiy;q=0.5 - no

It's obvious that issue in gzip server compression

**Comment by amosavian** [comment]
So we should use DEFLATE to preserve network bandwidth, if server does have this compression method support :)

**Comment by amosavian** [comment]
Hey @evilutioner I want to release a new pod version. Would you mind fix this one or open a new PR based on latest commit?

**Comment by evilutioner** [comment]
@amosavian I will not update the version of FileProvider in my project, you can close this bug if you want.

**Pull request closed without merging**
